# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateField(default=datetime.date(2016, 7, 18)),
        ),
    ]
