# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0005_auto_20160715_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateField(default=datetime.date(2016, 7, 16)),
        ),
    ]
