# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=50, null=True)),
                ('request_desc', models.CharField(max_length=1500)),
                ('request_user', models.EmailField(max_length=50)),
                ('request_dentist', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
