# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.date(2016, 8, 14)),
        ),
    ]
